import "./globals.css";
import type { Metadata } from "next";
import { cookies } from "next/dist/client/components/headers";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import { setAccessToken } from "@/token";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const refreshTokenData = await fetch("http://localhost:4000/refresh_token", {
    method: "POST",
    credentials: "include",
    headers: { Cookie: cookies().toString() },
  });

  const data = await refreshTokenData.json();

  const accessToken = data.accessToken;

  setAccessToken(accessToken);

  return (
    <html lang="en">
      <body>
        <ApolloWrapper accessToken={accessToken}>
          <NavBar />
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
